debug: true

# only with tomcat servlet container 3.1
#server:
#  servlet:
#    context-path: /v1

spring:
  security:
    user:
      roles:
        - USER
      name: test
      password: test

    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${mockwebserver.url}/.well-known/jwks.json
